# docker-compose.yml file
version: '3'

services:

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  server1:
    image: nginx:1.16.0-alpine
    volumes:
      - ./index.html:/var/www/html
      - ./secondpage.html:/var/www/html

